"""Add company registration fields to User

Revision ID: b263195abc9b
Revises: 0a7b9e58f024
Create Date: 2026-01-04 15:32:42.568090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added import


# revision identifiers, used by Alembic.
revision: str = 'b263195abc9b'
down_revision: Union[str, Sequence[str], None] = '0a7b9e58f024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('application', 'internal_uid',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    op.add_column('user', sa.Column('company_registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('company_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_company_registration_number'), 'user', ['company_registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_company_registration_number'), table_name='user')
    op.drop_column('user', 'company_type')
    op.drop_column('user', 'company_registration_number')
    # op.alter_column('application', 'internal_uid',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    # ### end Alembic commands ###
